#  
<h1><center><bold>123cs0022 - ML Lab - 30/7/25</bold></center></h1>

# **Question 1 : Set Union**

In [7]:
n = int(input("n = "))
setA = set(map(int, input("Elements = ").split(" ")))
m = int(input("m = "))
setB = set(map(int, input("Elements = ").split(" ")))

ans = setA.union(setB)
print(len(ans))

n = 2
Elements = 1 2
m = 3
Elements = 1 2 3
3


# **Question 2 : Set Intersection Count**

In [8]:
n = int(input("n = "))
setA = set(map(str, input("Elements = ").split(" ")))
m = int(input("m = "))
setB = set(map(str, input("Elements = ").split(" ")))

ans = setA.intersection(setB)
print(len(ans))

n = 3
Elements = apple banana mango
m = 2
Elements = apple papaya
1


# **Question 3 : Set Symmetric Difference**

In [10]:
n = int(input("n = "))
setA = set(map(int, input("Elements = ").split(" ")))
m = int(input("m = "))
setB = set(map(int, input("Elements = ").split(" ")))

union = setA.union(setB)
intersection = setA.intersection(setB)
ans = union - intersection
print(ans)

n = 4
Elements = 4 2 6 8
m = 3
Elements = 2 5 7
{4, 5, 6, 7, 8}


# **Question 4 : Check Subset**

In [11]:
n = int(input("n = "))
setA = set(map(int, input("Elements = ").split(" ")))
m = int(input("m = "))
setB = set(map(int, input("Elements = ").split(" ")))

ans = setA.issubset(setB)
print(ans)

n = 3
Elements = 1 2 3
m = 5
Elements = 1 2 3 4 5
True


# **Question 5 : Set Difference**

In [12]:
n = int(input("n = "))
setA = set(map(int, input("Elements = ").split(" ")))
m = int(input("m = "))
setB = set(map(int, input("Elements = ").split(" ")))

ans = setA.difference(setB)
print(ans)

n = 5
Elements = 1 2 3 4 5
m = 3
Elements = 2 4 6
{1, 3, 5}


In [13]:
!pip install numpy

# **Numpy**


In [14]:
import numpy as np

# **Question 1 : Array Manipulation with NumPy**

In [21]:
n = int(input("n = "))
arr = np.array(input("Elements = ").split(" ")).astype(int)

even_mask = arr % 2 == 0
arr[even_mask] *= 2
arr[~even_mask] //= 2

print(arr)

n = 5
Elements = 2 3 4 5 6
[ 4  1  8  2 12]


# **Question 2 : Matrix Diagonal Sum using NumPy**

In [34]:
n = int(input("n = "))
arr = np.array([[int(x) for x in input(f"Elements of row {i}: ").split()] for i in range(n)])

diag1 = np.sum(np.diag(arr))
diag2 = np.sum(np.diag(np.fliplr(arr)))

print(abs(diag1 - diag2))

n = 3
Elements of row 0: 11 2 4
Elements of row 1: 4 5 6
Elements of row 2: 10 8 -12
15


# **Question 3 : Reshape Array using NumPy**

In [39]:
n, rows, cols = map(int, (input("n, rows, cols = ").split(" ")))
arr = np.array(input("Elements = ").split(" ")).astype(int)

if len(arr) != rows * cols:
    print(-1)
else:
    reshaped_arr = arr.reshape(rows, cols)
    print(reshaped_arr)

n, rows, cols = 6 2 3
Elements = 1 2 3 4 5 6
[[1 2 3]
 [4 5 6]]


# **Question 4 : Element-wise Operations on Two Arrays**

In [40]:
n = int(input("n = "))
arr = np.array(input("Elements = ").split(" ")).astype(int)
brr = np.array(input("Elements = ").split(" ")).astype(int)

print(arr + brr)
print(arr - brr)
print(arr * brr)
print(arr // brr)

n = 4
Elements = 2 4 6 8
Elements = 1 2 3 4
[ 3  6  9 12]
[1 2 3 4]
[ 2  8 18 32]
[2 2 2 2]


# **Question 5 : Find Unique Elements Using NumPy**

In [45]:
n = int(input("n = "))
arr = set(map(int, np.array(input("Elements = ").split(" ")).astype(int)))

print(arr)

n = 10
Elements = 4 5 6 5 4 7 8 6 9 7
{4, 5, 6, 7, 8, 9}


# **Question 6 : Boolean Indexing with NumPy**

In [46]:
n = int(input("n = "))
arr = np.array(input("Elements = ").split(" ")).astype(int)
t = int(input("t = "))

filtered_arr = arr[arr > t]
print(filtered_arr)

n = 6
Elements = 3 10 15 8 6 2
t = 7
[10 15  8]
